name: Feature request
description: Suggest an idea for Home Assistant Notes
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: Describe the use case, not just the solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Proposed solution or alternatives you considered
